homework_2
Hlupik77/tobedev_course_2020_homework pull request #3
Opened 2020-03-05 21:19 UTC by Hlupik77

добавлен for (let key in phoneBook)

2020-03-05 23:32 UTC, rmuhamedgaliev requested changes

2020-03-05 23:32 UTC, rmuhamedgaliev commented on homework_2/index.js
> +    };
Только форматирование поправь.

2020-03-06 15:56 UTC, Hlupik77 commented on homework_2/index.js
> +    };
Отформатировал

2020-03-06 21:14 UTC, rmuhamedgaliev approved these changes

2020-03-06 21:15 UTC, merged